version: "3"

services:
  #database service
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ajlal121
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: ajlal
      MYSQL_PASSWORD: Ajlal121
    volumes:
      - mysql_vol:/var/lib/mysql

  #Wordpress
  wordpress:
    depends_on:
      - mysql_db
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: ajlal
      WORDPRESS_DB_PASSWORD: Ajlal121
      WORDPRESS_DB_NAME: wordpress_database
    volumes:
      - wordpress:/var/www/html

volumes:
  mysql_vol:
  wordpress:
